jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          pyinstaller_ver: '==6.11.1'
          spec: 'Script/init/setup.spec'
          requirements: 'Script/requirements.txt'
          options: --onefile, --name "setup.exe", --windowed
          spec_options: # any custom arguments you want like: `--debug`
      - name: Create Another Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          pyinstaller_ver: '==6.11.1'
          spec: 'Script/main/auto_login.spec'
          requirements: 'Script/requirements.txt'
          options: --onedir, --windowed, --icon "Script/main/wifi_icon_256x256.ico"
          spec_options: # any custom arguments you want like: `--debug`